import type { Task } from "./types";

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    sprintId: "sprint-14",
    title: "슬라임 몬스터 돌진 AI FSM 구현",
    status: "Todo",
    priority: "High",
    assignee: { name: "김도윤", role: "Programmer" },
    startDate: "2026-10-07",
    dueDate: "2026-10-11",
    attachments: [{ id: "att-1", name: "slime_run.spine", kind: "spine" }],
    domainId: "domain-client-programming",
  },
  {
    id: "task-2",
    sprintId: "sprint-14",
    title: "로비 UI 피그마 시안 깎기",
    status: "Todo",
    priority: "Medium",
    assignee: { name: "이서연", role: "Designer" },
    startDate: "2026-10-06",
    dueDate: "2026-10-08",
    attachments: [
      { id: "att-2", name: "로비 UI Figma 시안", kind: "figma", url: "https://figma.com/file/lobby-ui" },
    ],
    domainId: "domain-ui-ux-art",
  },
  {
    id: "task-3",
    sprintId: "sprint-14",
    title: "인벤토리 슬롯 드래그 앤 드롭",
    status: "Todo",
    priority: "Low",
    assignee: { name: "박지훈", role: "Programmer" },
    startDate: "2026-10-09",
    dueDate: "2026-10-13",
    attachments: [{ id: "att-3", name: "item_data_table.xlsx", kind: "spreadsheet" }],
    domainId: "domain-client-programming",
  },
  {
    id: "task-4",
    sprintId: "sprint-14",
    title: "추출 지점(익스필) 사운드 이펙트 믹싱",
    status: "In Progress",
    priority: "Medium",
    assignee: { name: "최민아", role: "Sound" },
    startDate: "2026-10-03",
    dueDate: "2026-10-07",
    attachments: [{ id: "att-4", name: "waveform_reference.png", kind: "image" }],
    domainId: "domain-sound",
  },
  {
    id: "task-5",
    sprintId: "sprint-14",
    title: "플레이어 피격 리액션 Spine 애니메이션",
    status: "In Progress",
    priority: "High",
    assignee: { name: "정하늘", role: "Animator" },
    startDate: "2026-10-01",
    dueDate: "2026-10-10",
    attachments: [
      { id: "att-5", name: "player_hit_reaction.spine", kind: "spine" },
      { id: "att-6", name: "VFX 참고 Figma", kind: "figma", url: "https://figma.com/file/player-vfx-ref" },
    ],
    domainId: "domain-ui-ux-art",
  },
  {
    id: "task-6",
    sprintId: "sprint-14",
    title: "총기 반동 커브 밸런싱",
    status: "QA",
    priority: "High",
    assignee: { name: "김도윤", role: "Programmer" },
    startDate: "2026-09-28",
    dueDate: "2026-10-06",
    attachments: [{ id: "att-7", name: "build_alpha_0.7.2.zip", kind: "build" }],
    domainId: "domain-client-programming",
  },
  {
    id: "task-7",
    sprintId: "sprint-14",
    title: "매칭 대기열 타임아웃 버그 검증",
    status: "QA",
    priority: "Medium",
    assignee: { name: "오세훈", role: "QA" },
    startDate: "2026-10-02",
    dueDate: "2026-10-05",
    domainId: "domain-server",
  },
  {
    id: "task-8",
    sprintId: "sprint-13",
    title: "메인 타이틀 로고 애니메이션",
    status: "Done",
    priority: "Low",
    assignee: { name: "이서연", role: "Designer" },
    startDate: "2026-09-23",
    dueDate: "2026-09-29",
    attachments: [
      { id: "att-8", name: "title_logo.spine", kind: "spine" },
      { id: "att-9", name: "타이틀 로고 Figma", kind: "figma", url: "https://figma.com/file/title-logo" },
    ],
    domainId: "domain-ui-ux-art",
  },
  {
    id: "task-9",
    sprintId: "sprint-13",
    title: "장비 강화 시스템 기획서 1차 검토",
    status: "Done",
    priority: "Medium",
    assignee: { name: "박지훈", role: "PM" },
    startDate: "2026-09-21",
    dueDate: "2026-09-27",
    domainId: "domain-game-design",
  },
  {
    id: "task-10",
    sprintId: "sprint-14",
    title: "매칭 대기열 타임아웃 버그 우선순위 조율",
    status: "In Progress",
    priority: "High",
    assignee: { name: "나", role: "PM" },
    startDate: "2026-10-02",
    dueDate: "2026-10-05",
    domainId: "domain-server",
  },
  {
    id: "task-11",
    sprintId: "sprint-14",
    title: "신규 무기 밸런싱 기획안 1차 승인",
    status: "Todo",
    priority: "High",
    assignee: { name: "나", role: "PM" },
    startDate: "2026-10-06",
    dueDate: "2026-10-08",
    domainId: "domain-game-design",
  },
  {
    id: "task-12",
    sprintId: "sprint-14",
    title: "이번 주 스프린트 리뷰 자료 정리",
    status: "Todo",
    priority: "Medium",
    assignee: { name: "나", role: "PM" },
    startDate: "2026-10-05",
    dueDate: "2026-10-07",
  },
  {
    id: "task-13",
    sprintId: "sprint-15",
    title: "보스전 2페이즈 패턴 구현",
    status: "Todo",
    priority: "High",
    assignee: { name: "김도윤", role: "Programmer" },
    startDate: "2026-10-14",
    dueDate: "2026-10-24",
    domainId: "domain-client-programming",
  },
  {
    id: "task-14",
    sprintId: "sprint-15",
    title: "세이브 데이터 마이그레이션",
    status: "Todo",
    priority: "High",
    assignee: { name: "한지우", role: "Server" },
    startDate: "2026-10-12",
    dueDate: "2026-10-20",
    domainId: "domain-server",
  },
  {
    id: "task-15",
    sprintId: "sprint-14",
    title: "캐릭터 리깅 v3 적용",
    status: "In Progress",
    priority: "Medium",
    assignee: { name: "정하늘", role: "Animator" },
    startDate: "2026-10-01",
    dueDate: "2026-10-10",
    attachments: [{ id: "att-15", name: "hero_rig_v3.spine", kind: "spine" }],
    domainId: "domain-ui-ux-art",
  },
  {
    id: "task-16",
    title: "튜토리얼 대사 스크립트 정리",
    status: "Todo",
    priority: "Low",
    assignee: { name: "박지훈", role: "PM" },
    startDate: "2026-10-16",
    dueDate: "2026-10-22",
    domainId: "domain-game-design",
  },
];
